### ISSUE TITLE
curious about the statistics of 'level'

### ISSUE THREAD

**Issue by countcain** [sqrlab/GitView#3]
In the demo page, I can see a level select element whose values can be none, method and statement. This is cool. But is it only available for java? Can it support other languages?

**Comment by dataBaseError** [comment]
Thank you for your feedback. Currently Java is the only supported language. The reason for the limited support is that a parser is used to differentiate between comment and code blocks. A second parser is then used to identify method blocks. Support for other languages is definitely possible however this requires an implementation of the both of the parsers described above for the specific language.

I should note that even though the documentation parser was written for java, it will most likely work with C++. This is because the documentation symbols used by both languages are the same. However other languages such as Ruby or Python the parser will not be able to identify the documentation since they use different comment symbols.

The second language specific parser, the method identification, is fairly Java specific. The parser will most likely not properly identify methods for C++ since the method signatures are different from Java.
